[package]
name = "captcha-gen"
version = "0.1.1"
edition = "2024"

[dependencies]
captcha-rs = { git = "https://github.com/ParkSnoopy/captcha-rs.git", branch = "main-captcha-gen" }
either = "1.15"
image = "0.25"
lazy_static = "1.5"
rand = "0.9"
rayon = "1.11"
